# port => external:internal
# volumes => volume_name:internal_storage_location
version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672 # for services to communicate with rabbitmq
      - 15672:15672 # navigate to rabbitmq portal
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq #rabbitmq uses this to store data. if dont specify it, it gets randomly generated. and rabbitmq stores data differently each time

volumes:
  mongodbdata:
  rabbitmqdata:
